baseURL = "https://lingo-db.com"
languageCode = "en-us"
title = "LingoDB - Revolutionizing Data Processing with Compiler Technology"

disqusShortname = "username" # delete this to disable disqus comments

[params]
    author = "Michael Jungmair"
    copyright = "Technische Universität München – Fakultät für Informatik: Lehrstuhl III: Datenbanksysteme"
    githubUsername = "#"
    accent = "#007bff"
    showBorder = true
    backgroundColor = "#f0f0f0"
    font = "Nunito" # should match the name on Google Fonts!

[markup]
  [markup.highlight]
    anchorLineNos = false
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'pygments'
    tabWidth = 4

[[menu.main]]
    url = "#features"
    name = "Features"
    Identifier = "features"
    weight = 1

[[menu.main]]
    url = "#research"
    name = "Research"
    Identifier = "research"
    weight = 2

[[menu.main]]
    url = "#publications"
    name = "Publications"
    Identifier = "publications"
    weight = 3

[[menu.main]]
    url = "#team"
    name = "Team"
    Identifier = "team"
    weight = 4

[[menu.main]]
    url = "#contact"
    name = "Contact"
    Identifier = "contact"
    weight = 5

# Social icons to be shown on the right-hand side of the navigation bar.
# The "name" field should match the name of the icon in Font Awesome.
# The list of available icons can be found at http://fontawesome.io/icons.



[[menu.icon]]
    url = "mailto:info@lingo-db.com"
    name = "envelope"
    weight = 2
